### ISSUE TITLE
create document templates / sample documents to refer to as "best practice"

### ISSUE THREAD

**Issue by PeterNerlich** [ubam/infrastructure#4]
Lead the way to uniform and highly informative by design documents by creating (multiple) samples/templates (differences e.g. for internal documents and external docs meant for the public, like detailed install instructions for newcomers etc.)

My suggestion for "internal" documents btw.: Similar to [Group Creation Guidelines](https://github.com/ubam/community/blob/master/Group%20Creation%20Guidelines.md)
- # Headline (= doc file name)
- *very short description*
- **Purpose:** semi-elaborate paragraph about the base situation that gave birth to the idea presented (or whatever) and the (original?) idea itself
- Current state: **[ state ]** (if applicable | **state** like planning only, testing, etc.)
- ## Headlines.....
- content......

**Comment by Acid-Override** [comment]
wow... you never cease to amaze me.

**Comment by lionelb123** [comment]
If the document is a proposal, it would be helpful to have a section about alternatives (including taking no action) and a brief comment on why one preferred over the other ?

**Comment by PeterNerlich** [comment]
This issue was moved to ubam/doc-templates#1
